name: Sanity check

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.x
          
      - name: Provide internal config file
        env:
          SUPER_CONFIG: ${{ secrets.CONFIG }}
        run: |
          echo $SUPER_CONFIG > /home/runner/work/msoc-web/msoc-web/MSOC.Backend/config.ini

      - name: Restore NuGet packages
        run: dotnet restore

      - name: Run tests
        run: dotnet test MSOC.Backend.Tests -c Release -v n --nologo --no-restore
